name: Postman PR Diff

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  postman-pr-diff:
    name: Postman collection diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: ./
        with:
          github-token: ${{ github.token }}
